In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('loan_approval_dataset.csv')
df.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4269 entries, 0 to 4268
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   loan_id                   4269 non-null   int64
 1   no_of_dependents          4269 non-null   int64
 2   education                 4269 non-null   object
 3   self_employed             4269 non-null   object
 4   income_annum              4269 non-null   int64
 5   loan_amount               4269 non-null   int64
 6   loan_term                 4269 non-null   int64
 7   cibil_score               4269 non-null   int64
 8   residential_assets_value  4269 non-null   int64
 9   commercial_assets_value   4269 non-null   int64
 10  luxury_assets_value       4269 non-null   int64
 11  bank_asset_value          4269 non-null   int64
 12  loan_status               4269 non-null   object
dtypes: int64(10), object(3)
memory usage: 433.7+ KB

In [4]:
df['education'].value_counts

<bound method IndexOpsMixin.value_counts of 0            Graduate
1        Not Graduate
2            Graduate
3            Graduate
4        Not Graduate
            ...
4264         Graduate
4265     Not Graduate
4266     Not Graduate
4267     Not Graduate
4268         Graduate
Name: education, Length: 4269, dtype: object>

#### Question 1: Probability

- Using the loan_approval_dataset.csv dataset, answer the following questions:
- Let:
   + A = Applicant is a Graduate
   + B = Applicant is Self-Employed
   + C = Loan is Approved

##### Part A: Marginal (Unconditional) Probability
============================================
- Calculate the following probabilities:

1. What is the probability that a randomly selected applicant is a Graduate?

In [5]:
total = len(df)
print(total)

4269

In [6]:
applicant_graduate = df[ df['education'] == ' Graduate' ]
total_applicant_graduate = len(applicant_graduate)
print(total_applicant_graduate)
p_applicant_graduate = total_applicant_graduate/total
print(p_applicant_graduate)

2144
0.502225345514172

2. What is the probability that a randomly selected applicant is Self-Employed?

In [7]:
df['self_employed'].value_counts()

self_employed
Yes    2150
No     2119
Name: count, dtype: int64

In [8]:
applicant_self_employed= df[df['self_employed']==" Yes"]
total_applicant_self_employed = len(applicant_self_employed)
p_applicant_self_employed = total_applicant_self_employed/total
print(p_applicant_self_employed)

0.5036308268915437


3. What is the probability that a randomly selected applicant receives Loan Approval?

In [9]:
loan_approved= df[df['loan_status']=="Approved"]
total_loan_approved = len(loan_approved)
p_loan_approved = total_loan_approved/total
print(p_loan_approved)

0.622159756383228

### Part B: Joint (Unconditional) Probability
=========================================
- Calculate the following probabilities:

4. What is the probability that an applicant is a Graduate and receives loan approval?

In [10]:
applicant_graduate_loanApproved = df[ (df['education']==" Graduate") & (df['loan_status']=="Approved") ]
total_graduate_loanApproved = len(applicant_graduate_loanApproved)
p_graduate_loanApproved = total_graduate_loanApproved / total
print(p_graduate_loanApproved)

0.31365659405012886

5. What is the probability that an applicant is Self-Employed and receives loan approval?

In [11]:
applicant_SelfEmp_loanApproved=df[(df['self_employed']==" Yes")  & (df['loan_status']=="Approved") ]
total_SelfEmp_loanApproved=len(applicant_SelfEmp_loanApproved)
p_SelfEmp_loanApproved=total_SelfEmp_loanApproved/total
print(p_SelfEmp_loanApproved)

0.3134223471539002

6. What is the probability that an applicant is both Graduate and Self-Employed?

In [12]:
applicant_graduate_selfEmp = df[ (df['education']==' Graduate') & (df['self_employed']==" Yes")]
p_graduate_selfEmp = len(applicant_graduate_selfEmp) /total
print(p_graduate_loanApproved)

0.31365659405012886

#### Part C: Conditional Probability
===============================
Calculate the following probabilities:

7. What is the probability that an applicant receives loan approval given that the applicant is a Graduate?
8. What is the probability that an applicant receives loan approval given that the applicant is Self-Employed?
9. What is the probability that an applicant is a Graduate given that the loan was approved?
10. What is the probability that an applicant is Self-Employed given that the loan was approved?

7. What is the probability that an applicant receives loan approval given that the applicant is a Graduate?

In [13]:
p_loanApproved_given_graduate = p_graduate_loanApproved / p_applicant_graduate
print(p_loanApproved_given_graduate)

0.6245335820895522


8. What is the probability that an applicant receives loan approval given that the applicant is Self-Employed?

In [14]:
p_loanApproved_given_selfEmp = p_SelfEmp_loanApproved / p_applicant_self_employed
print(p_loanApproved_given_selfEmp)

0.6223255813953489

9. What is the probability that an applicant is a Graduate given that the loan was approved?
    - Using Baye's theorem - 
      - p(graduate|loan_approved) = [ p(loan_approved|graduate) * p(graduate) ] / p(loan_approved)
        + (0.6245335820895522 * 0.502225345514172) / 0.622159756383228 = 0.5041415662650602

In [15]:
p_graduate_given_loanApproved=p_graduate_loanApproved/p_loan_approved
print(p_graduate_given_loanApproved)

0.5041415662650602


10. What is the probability that an applicant is Self-Employed given that the loan was approved?
    - Using Bayes theorem -
      - p(self-emp | loan_Approved) = [ p(loan_approved | self_emp) * p(self_emp) ] / p(loan_approved)
        + ( 0.6223255813953489 * 0.5036308268915437 ) / 0.622159756383228 = 0.5037650602409638

In [16]:
p_selfEmp_given_loanApproved = p_SelfEmp_loanApproved / p_loan_approved
print(p_selfEmp_given_loanApproved)

0.5037650602409638

0.5037650602409638

0.3134223471539002

#### Part D: Interpretation
======================
Based on your results:

11. Are Graduates more likely to receive loan approval than the overall applicant population? Justify using probabilities.
    + **Ans:** Yes, since `probability` of loan is approved given applicant is graduate is `0.624` so there are high
       chances of getting loan is approved than overall applicant population

12. Are Self-Employed applicants more likely or less likely to receive loan approval compared to the overall population?
    + **Ans** Yes, since `probability` of loan is approved given applicant is self employed is `0.622` so there are high
       chances of getting loan is appoved than overall population

14. Which factor appears to have a stronger association with loan approval:
Education status, or Self-employment status?
     + **Ans** The Education status has slightly stronger association with loan approval, since probability -
         + probability of education status and loan approval is `0.624`
         + probability of Self-employment status and loan approval is `0.622`

### Bayes Theorem
Accept a new customer record (just the education status). Predict the chance that this new customer will get a loan. <br>
Incorporate this customer's data  into the current data. Repeat it for one more customer and predict for the second customer. <br>
Do the probabilities change ? If yes, by how much
- **Ans**: 
  1. P(loan_Approvd | Graduate) = `[ P(Graduate | Loan_Approved)*P(Loan_Approved) ] / P(Graduate)`
     - P(Graduate | Loan_Approved) = P(Graduate, Loan_Approved) / P(Loan_Approved) ... Conditional Probability
  2. P(loan_Approvd | Not Graduate) = `[ P(Not Graduate | Loan_Approved)*P(loan_Approved)] / P(Not Graduate)`
      - P(Not Graduate | Loan_Approved) = P(Not Graduate,Loan_Approved) / P(Loan_Approved) ... Conditional Probability

In [17]:
# A: Applicant is Graduate
# B: Loan is approved
# p(A|B) = p(A,B) / p(B)
applicant_graduate_loanApproved = df[ (df['education']==" Graduate") & (df['loan_status']=="Approved") ]
total_graduate_loanApproved = len(applicant_graduate_loanApproved)
p_graduate_loanApproved = total_graduate_loanApproved / total
print(p_graduate_loanApproved)

0.31365659405012886

In [18]:
loan_approved= df[df['loan_status']=="Approved"]
total_loan_approved = len(loan_approved)
p_loan_approved = total_loan_approved/total
print(p_loan_approved)

0.622159756383228

In [19]:
graduate = df[df['education'] == " Graduate"]
total_graduate=len(graduate)
p_graduate = total_graduate / total
print(p_graduate)

0.502225345514172

In [20]:
# A: Applicant is Not Graduate
# B: Loan is approved
# p(A|B) = p(A,B) / p(B)
not_graduate_loan_approved = df[ (df['education']==" Not Graduate" )  & (df['loan_status'] == "Approved") ]
total_notGraduate_loanAppr=len(not_graduate_loan_approved)
p_not_graduate_loan_approved = total_notGraduate_loanAppr / total
print(p_not_graduate_loan_approved)

0.3085031623330991

In [21]:
not_graduate = df[df['education']==" Not Graduate"]
total_not_graduate = len(not_graduate)
p_not_graduate = total_not_graduate / total
print(p_not_graduate)

0.4977746544858281

In [22]:
for i in range(2):
    education= int(input('Enter education: \n1.Graduate \n2.Not Graduate\n Enter choice: '))
    if education==1:
                   p_graduateGivenLoanApproved = p_graduate_loanApproved / p_loan_approved
                   p_loan_approved_given_graduate = (p_graduateGivenLoanApproved * p_loan_approved)/p_graduate
                   print(f'Probability of getting loan: {p_loan_approved_given_graduate}',"\n")
    elif education==2:
        p_notGraduateGivenLoanApproved = p_not_graduate_loan_approved / p_loan_approved
        p_loan_approved_given_notGraduate = (p_notGraduateGivenLoanApproved * p_loan_approved ) / p_not_graduate
        print(f'Probability of getting loan: {p_loan_approved_given_notGraduate}',"\n")

Probability of getting loan: 0.6245335820895522

Probability of getting loan: 0.619764705882353

In [23]:
0.6245335820895522   - 0.619764705882353

0.004768876207199235

Yes, Probabilities change by `0.004768876207199235`

##### Q.2 Normal distribution - Diabates

 1. What is the probability that a randomly selected patient has a glucose level between 100 mg/dL and 140 mg/dL?
 2. What percentage of patients are expected to have a glucose level greater than 180 mg/dL?
 3. Determine the glucose level that separates the top 10% of patients from the remaining 90%.
 4. What is the probability that a patient's glucose level lies within one standard deviation of the mean glucose level?
 5. A patient has a glucose level of 200 mg/dL. Calculate the z-score and determine the probability that a randomly selected patient has a glucose level higher than this.
 6. A hospital can only perform expensive follow-up tests on the highest 5% of glucose readings. What glucose level should be used as the cutoff?
 7. What percentage of patients are expected to have glucose levels between the 25th percentile and the 75th percentile?
 8. Find the glucose level corresponding to the 30th percentile and interpret its meaning in the context of the dataset.
 9. What is the probability that a patient's glucose level is at least 20 mg/dL above the mean glucose level?
 10. Identify all patients whose glucose z-scores are greater than +2 or less than -2. What proportion of the dataset do these potentially unusual observations represent?

In [24]:
import scipy.stats as stats
from scipy.stats import zscore

In [25]:
df = pd.read_csv('diabetes.csv')
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [26]:
glucose_mean=df['Glucose'].mean()
glucose_std = df['Glucose'].std()
print(f'Mean of Glucose {glucose_mean}')
print(f'Standard deviation of Glucose {glucose_std}')

Mean of Glucose 120.89453125
Standard deviation of Glucose 31.97261819513622

In [27]:
# 1. What is the probability that a randomly selected patient has a glucose level between 100 mg/dL and 140 mg/dL?
prob_100_140_s = stats.norm.cdf(140, loc=glucose_mean, scale=glucose_std) - stats.norm.cdf(100, loc=glucose_mean, scale=glucose_std)
print(f"1. Probability (100 to 140 mg/dL): {prob_100_140_s:.2f}")

1. Probability (100 to 140 mg/dL): 0.47

In [28]:

zscore_100 = ( 100 - 120.8945 ) / 31.9726
zscore_140 = (140 - 120.8945 ) / 31.9726
print(zscore_100, zscore_140)

-0.6535126952453036 0.5975585344951617

In [29]:
probability_100 = stats.norm.cdf(zscore_100) 
print(probability_100)

0.2567129038562427

In [30]:
probability_140 = stats.norm.cdf(zscore_140)
print(probability_140)

0.7249327305137077

In [31]:
round((0.7249327305137077 + 0.2567129038562427),5)

0.98165

In [32]:
# Q2: P(X > 180)
# ( 180 - glucose_mean ) / glucose_std = 1.8486277348093851
# 0.5 - 0.4671 = 0.032899999999999985
prob_gt_180_s = 1 - stats.norm.cdf(180, glucose_mean, glucose_std)
print(f"2. Percentage (> 180 mg/dL): {prob_gt_180_s}\n")

2. Percentage (> 180 mg/dL): 0.032255792517573934

In [33]:
# 3. Determine the glucose level that separates the top 10% of patients from the remaining 90%
glucose_90th = stats.norm.ppf(0.90,loc=glucose_mean,scale=glucose_std)
print("\n 3. Glucose level for top 10%(90th percentile)")
print(f'{glucose_90th:.2f} mg/dl')

 3. Glucose level for top 10%(90th percentile)
161.87 mg/dl

In [34]:
# 4. What is the probability that a patient's glucose level lies within one standard deviation of the mean glucose level?
lower = glucose_mean - glucose_std
upper = glucose_mean + glucose_std
prob_within_1sd = (stats.norm.cdf( (upper - glucose_mean)/glucose_std) - stats.norm.cdf((lower - glucose_mean)/glucose_std)  )
print("\n4. Probability within one standard deviation")
print(f'{prob_within_1sd: .4f} ({prob_within_1sd*100:.2f})' )

4. Probability within one standard deviation
 0.6827 (68.27)

In [35]:
# 5. A patient has a glucose level of 200 mg/dL. Calculate the z-score and determine the probability that a 
#   randomly selected patient has a glucose level higher than this.
z = (200 - glucose_mean) / glucose_std 
prob = 1 - stats.norm.cdf(z)
print("\n5. Patient Glucose = 200")
print(f"zscore = {z}")
print(f'Probability that Glucose > 200 = {prob:.4f} ({prob*100:.2f}%)')

5. Patient Glucose = 200
zscore = 2.474162993696706
Probability that Glucose > 200 = 0.0067 (0.67%)

In [36]:
# 6 A hospital can only perform expensive follow-up tests on the highest 5% of glucose readings. 
# What glucose level should be used as the cutoff?
glucose_95th = stats.norm.ppf(0.95,loc=glucose_mean,scale=glucose_std)
print("\n 6. Glucose level for top 5%(95th percentile)")
print(f'cutoff glucose level: {glucose_95th:.2f} mg/dl')

 6. Glucose level for top 5%(95th percentile)
cutoff glucose level: 173.48 mg/dl

In [37]:
# 7. What percentage of patients are expected to have glucose levels between the 25th percentile and the 75th percentile?
glucose_25th = stats.norm.ppf(0.25,loc=glucose_mean,scale=glucose_std)
glucose_75th = stats.norm.ppf(0.75,loc=glucose_mean,scale=glucose_std)
print(glucose_25th,glucose_75th)
prob_bet_25th_and_75th = stats.norm.cdf(glucose_75th,loc=glucose_mean,scale=glucose_std) - stats.norm.cdf(glucose_25th,loc=glucose_mean,scale=glucose_std)
print("\nProbability between 25th and 75th percentile: ",prob_bet_25th_and_75th)
print(f"percentage: {prob_bet_25th_and_75th:.4f}")

99.32932799044787 142.45973450955213

Probability between 25th and 75th percentile:  0.5
percentage: 0.5000

In [38]:
# 8. Find the glucose level corresponding to the 30th percentile and interpret its meaning in the context of the dataset.
p8 = stats.norm.ppf(0.30, glucose_mean, glucose_std)
print(f"Q8: {p8:.2f} mg/dL")

## 30% values in the dataset are below 104.13 mg/dl

Q8: 104.13 mg/dL

In [39]:
# 9. What is the probability that a patient's glucose level is at least 20 mg/dL above the mean glucose level?
zscore_20 = ((glucose_mean+20)-glucose_mean) / glucose_std
prob_above20 = 1-stats.norm.cdf(zscore_20)
print('probability above 20mg/dl:',prob_above20)

probability above 20mg/dl: 0.26580990735979604

In [40]:
# 10. Identify all patients whose glucose z-scores are greater than +2 or less than -2. 
#    What proportion of the dataset do these potentially unusual observations represent?
z_scores = (df['Glucose'] - glucose_mean) / glucose_std
outliers = df['Glucose'][(z_scores > 2) | (z_scores < -2)]
print(f"Q10 Outliers: {outliers}, Proportion: {(len(outliers)/len(df['Glucose']) ) *100:.2f}%")

Q10 Outliers: 8      197
13     189
22     196
56     187
62      44
75       0
154    188
182      0
185    194
206    196
228    197
258    193
260    191
319    194
342      0
349      0
359    196
360    189
399    193
408    197
440    189
489    194
498    195
502      0
545    186
546    187
549    189
561    198
579    197
595    188
661    199
675    195
680     56
715    187
748    187
759    190
Name: Glucose, dtype: int64, Proportion: 4.69%

Q10 Outliers: 8      197
13     189
22     196
56     187
62      44
75       0
154    188
182      0
185    194
206    196
228    197
258    193
260    191
319    194
342      0
349      0
359    196
360    189
399    193
408    197
440    189
489    194
498    195
502      0
545    186
546    187
549    189
561    198
579    197
595    188
661    199
675    195
680     56
715    187
748    187
759    190
Name: Glucose, dtype: int64, Proportion: 4.69 %

### Q3 Two-Sample t test

1. Titanic: Is the average age of male passengers significantly different from the average age of female passengers ?

In [41]:
from scipy import stats

In [42]:
df = pd.read_csv('titanic.xls')
df.head()

   survived  pclass  gender   age  sibsp  parch     fare embarked deck
0         0       3    male  22.0      1      0   7.2500        S  NaN
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
4         0       3    male  35.0      0      0   8.0500        S  NaN

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   gender    891 non-null    object
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object
 8   deck      203 non-null    object
dtypes: float64(2), int64(4), object(3)
memory usage: 62.8+ KB

In [44]:
df = df.dropna()

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 182 entries, 1 to 889
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  182 non-null    int64
 1   pclass    182 non-null    int64
 2   gender    182 non-null    object
 3   age       182 non-null    float64
 4   sibsp     182 non-null    int64
 5   parch     182 non-null    int64
 6   fare      182 non-null    float64
 7   embarked  182 non-null    object
 8   deck      182 non-null    object
dtypes: float64(2), int64(4), object(3)
memory usage: 14.2+ KB

In [46]:
df.isnull().sum()

survived    0
pclass      0
gender      0
age         0
sibsp       0
parch       0
fare        0
embarked    0
deck        0
dtype: int64

In [47]:
male = df[df['gender']=="male"]
female = df[df['gender']=="female"]

    survived  pclass gender   age  sibsp  parch      fare embarked deck
6          0       1   male  54.0      0      0   51.8625        S    E
21         1       2   male  34.0      0      0   13.0000        S    D
23         1       1   male  28.0      0      0   35.5000        S    A
27         0       1   male  19.0      3      2  263.0000        S    C
54         0       1   male  65.0      0      1   61.9792        C    B

In [48]:
# take the sample
male_sample = male.sample(n=30,replace=True)
female_sample = female.sample(n=30,replace=True)

In [49]:
# Perform two sample t-test
t_statistic,p_value = stats.ttest_ind(male_sample['age'],female_sample['age'])
# Degree of Freedom
dof = len(male_sample) + len(female_sample)  - 2

alpha = 0.05 

if p_value < alpha:
    print('There is a significant difference')
else:
    print('There is not significant difference')

There is a significant difference

In [50]:
# Find the critical value
critical_value= stats.t.ppf(1-alpha , dof)

if abs(t_statistic) > critical_value:
    print('There is a significant difference')
else:
    print('there is no significant difference')

There is a significant difference

In [51]:
# Print the results
print('T-stastic: ', t_statistic)
print('P-value: ',p_value)
print('Critical value: ',critical_value)

T-stastic:  2.092243393272931
P-value:  0.04080352985453393
Critical value:  1.671552762454859

2. Titanic: Is there a significant difference in average age between surviors and non-survivors?

In [52]:
survived = df[df['survived']==0]
not_survived = df[df['survived']==1]

In [53]:
# take the sample
survived_sample = survived.sample(n=30,replace=True)
not_survived_sample = not_survived.sample(n=30,replace=True)

In [54]:
# Perform two sample t-test
t_statistic,p_value = stats.ttest_ind(survived_sample['age'],not_survived_sample['age'])
# Degree of Freedom
dof = len(survived_sample) + len(not_survived_sample)  - 2

alpha = 0.05 

if p_value < alpha:
    print('There is a significant difference')
else:
    print('There is not significant difference')

There is a significant difference

In [55]:
# Find the critical value
critical_value= stats.t.ppf(1-alpha , dof)

if abs(t_statistic) > critical_value:
    print('There is a significant difference')
else:
    print('there is no significant difference')

There is a significant difference

In [56]:
# Print the results
print('T-stastic: ', t_statistic)
print('P-value: ',p_value)
print('Critical value: ',critical_value)

T-stastic:  3.0603123996123416
P-value:  0.003346080089094356
Critical value:  1.671552762454859

3. Diabetes: Is the mean glucose level significantly different between diabetic and non-diabetic patient?

In [57]:
df = pd.read_csv('diabetes.csv')
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [58]:
diabetic = df[df['Outcome']==1]
non_diabetic = df[df['Outcome']==0]

In [59]:
# take a sample
diabetic_sample = diabetic.sample(n=30,replace=True)
non_diabetic_sample = non_diabetic.sample(n=30,replace = True)

In [60]:
# Perform two sample independent t test
t_statistic,p_value=stats.ttest_ind(diabetic_sample['Glucose'],non_diabetic_sample['Glucose'])

alpha = 0.05
if p_value < alpha:
    print('There is significant difference')
else:
    print('There is no significant difference')

There is significant difference

In [61]:
# Find the critical value
dof = len(diabetic_sample) + len(non_diabetic_sample) - 2
critical_value= stats.t.ppf(1-alpha , dof)

if abs(t_statistic) > critical_value:
    print('There is a significant difference')
else:
    print('there is no significant difference')

There is a significant difference

In [62]:
# Print the results
print('T-stastic: ', t_statistic)
print('P-value: ',p_value)
print('Critical value: ',critical_value)

T-stastic:  5.172617777503298
P-value:  2.997010765359015e-06
Critical value:  1.671552762454859

4. diabetes : Is there a significant difference in average BMI between diabetic and non-diabetic patient?

In [63]:
df = pd.read_csv('diabetes.csv')
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [64]:
diabetic = df[df['Outcome'] == 1]
non_diabetic = df[df['Outcome'] == 0]
diabetic_sample = diabetic.sample(n=30,replace=True)
non_diabetic_sample= diabetic.sample(n=30,replace=True)

In [65]:
# Perform two sample independent t test
t_statistic,p_value=stats.ttest_ind(diabetic_sample['BMI'],non_diabetic_sample['BMI'])

alpha = 0.05
if p_value < alpha:
    print('There is significant difference')
else:
    print('There is no significant difference')

There is no significant difference

In [66]:
# Print the results
print('T-stastic: ', t_statistic)
print('P-value: ',p_value)

T-stastic:  -0.6928453432868623
P-value:  0.4911716351109129

5. tips : do weekend customers spend more than weekday customer?

In [67]:
df= pd.read_csv('tips.xls')
df.head()

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3.560330e+15,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4.478070e+15,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6.011810e+15,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4.676140e+15,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4.832730e+15,Sun2251

In [68]:
weekend = df[ (df['day']=='Sun') | (df['day']=='Sat') ]
weekday = df[ (df['day']!='Sun') | (df['day']!='Sat') ]
weekend_sample = weekend.sample(n=30,replace = True)
weekday_sample = weekday.sample(n=30,replace = True)

In [69]:
t_stastic,p_value = stats.ttest_ind(weekend_sample['total_bill'],weekday_sample['total_bill'])

alpha = 0.05
if p_value < alpha:
    print('Reject H0 Null Hypothesis')
else:
    print('Fail to reject H0 Null Hypothesis(Null hypothesis accepted: weekend customers spend more)')

Fail to reject H0 Null Hypothesis(Null hypothesis accepted: weekend customers spend more)

In [70]:
# Print the results
print('T-stastic: ', t_statistic)
print('P-value: ',p_value)
print('Critical value: ',critical_value)

T-stastic:  -0.6928453432868623
P-value:  0.9197906856492998
Critical value:  1.671552762454859

### Q.4 Run a `Paired T-test` on 
1. pre and post exercise heart rate analysis
   - columns: Resting Heart rate Before and Resting Heart Rate After
2. Hypothermia dataset (in ou github repo) on columns t.1 and t.2

In [71]:
df = pd.read_csv('heart_rate_data.csv')
df.head()

,Age,Sleep Hours,Exercise Frequency (Days/Week),Resting Heart Rate Before,Resting Heart Rate After,Max Heart Rate During Exercise
0,37,9.1,7,78,71,142
1,46,7.8,5,80,73,153
2,27,7.1,3,56,50,153
3,51,10.7,4,67,61,145
4,32,6.6,6,85,76,140

In [72]:
heart_rate = df[['Resting Heart Rate Before','Resting Heart Rate After']]
heart_rate_sample = heart_rate.sample(n=30)

In [73]:
tstat,p_value = stats.ttest_rel(heart_rate_sample['Resting Heart Rate Before'], heart_rate_sample['Resting Heart Rate After'])
alpha = 0.05
if p_value < alpha:
    print('Reject Null Hypothesis')
else:
    print('Fail to reject Null Hypothesis (Accept Null Hypothesis)')

Reject Null Hypothesis

2. Hypothermia dataset

In [74]:
df = pd.read_csv('Hypothermia.csv')
df.head()

,case,code,date,time,weight,t.nur,t.or,t.1,t.2,t.3,t.4,t.5,t.6
0,1,98887,12.0,20.30,2550,29,28,34.0,35.1,,,,
1,2,98528,11.0,18.10,1200,29,23,29.0,33.0,36.5,36.8,,
2,3,95723,3.0,10.24,2650,31,32,31.0,36.8,,,,
3,4,97694,8.0,0.30,800,27,22,32.0,34.0,35,35.5,36,36.5
4,5,96892,6.0,6.20,1880,30,30,32.2,36.6,,,,

In [75]:
t = df[['t.1','t.2']]
t_sample = t.sample(n=30)

In [76]:
t_sample.head()

      t.1   t.2
120  35.5  36.2
157  35.6  36.8
123  35.5  36.6
188  35.8  37.0
118  35.5  36.0

In [77]:

tstat,p_value = stats.ttest_rel(t_sample['t.1'], t_sample['t.2'])
alpha = 0.05
if p_value < alpha:
    print('Reject Null Hypothesis')
else:
    print('Fail to reject Null Hypothesis (Accept Null Hypothesis)')

Reject Null Hypothesis

### Q.5 ANOVA
1. Using ANOVA, determine whether Age differs significantly across different passengers Classes (Pclass) in titaninc dataset.
2. For Tips data, determine whether the Tip Percentgage (tip / total_bill *100) differs significantly across different days.
3. Create glucose categories (Low, Medium, High) and determine whether skin Thickness differs significantly  across these groups using ANOVA
4. For StudentsPerformance.csv, using ANOVA find if there is a significant difference in Maths marks depending on the level of parental education

1. Using ANOVA, determine whether Age differs significantly across different passengers Classes (Pclass) in titaninc dataset.

In [78]:
from scipy.stats import f_oneway

In [79]:
df = pd.read_csv('titanic.xls')
df.head()

   survived  pclass  gender   age  sibsp  parch     fare embarked deck
0         0       3    male  22.0      1      0   7.2500        S  NaN
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
4         0       3    male  35.0      0      0   8.0500        S  NaN

In [80]:
df.pclass.value_counts()

pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [81]:
s1 = df.age[df.pclass ==1 ]
s2 = df.age[df.pclass ==2 ]
s3 = df.age[df.pclass ==3 ]
fstat, pval = f_oneway(s1,s2,s3)

alpha = 0.05

if pval < alpha:
    print('Reject H0')
else:
    print('Do not reject H0')

Do not reject H0

2. For Tips data, determine whether the Tip Percentgage (tip / total_bill *100) differs significantly across different days.

In [82]:
df = pd.read_csv('tips.xls')
df.head()

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3.560330e+15,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4.478070e+15,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6.011810e+15,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4.676140e+15,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4.832730e+15,Sun2251

In [83]:
df['tip_percentage'] = (df['tip']/df['total_bill'])*100
df.head()

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_percentage
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3.560330e+15,Sun2959,5.944673
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4.478070e+15,Sun4608,16.054159
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6.011810e+15,Sun4458,16.658734
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4.676140e+15,Sun5260,13.978041
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4.832730e+15,Sun2251,14.680765

In [84]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [85]:
s1 = df.tip_percentage[df.day =='Thur' ]
s2 = df.tip_percentage[df.day =='Fri' ]
s3 = df.tip_percentage[df.day =='Sat' ]
s4 = df.tip_percentage[df.day =='Sun' ]

fstat, pval = f_oneway(s1,s2,s3,s4)

alpha = 0.05

if pval < alpha:
    print('Reject H0')
else:
    print('Do not reject H0')

Do not reject H0

3. Create glucose categories (Low, Medium, High) and determine whether skin Thickness differs significantly across these groups using ANOVA

In [86]:
df = pd.read_csv('diabetes.csv')
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [87]:
df['Glucose'].max()

199

In [88]:
arr = np.array(df['Glucose'])
low= np.percentile(arr,33.33)
med= np.percentile(arr,66.66)
print(low)
print(med)

s1 = df[df['Glucose'] < low]['SkinThickness']
s2 = df[(df['Glucose'] > low ) & (df['Glucose']<med)]['SkinThickness']
s2 = df[df['Glucose'] > med]['SkinThickness']

print(len(s1))
print(len(s2))
print(len(s3))

# s1 = df[df['Glucose'] < 70]['SkinThickness']
# s2 = df[(df['Glucose'] > 70 ) & (df['Glucose']<125)]['SkinThickness']
# s2 = df[df['Glucose'] > 125]['SkinThickness']

fstat, pval = f_oneway(s1,s2,s3)
print("pvalue: ",pval)
print("fstat:  ",fstat)

alpha = 0.05
if pval < alpha:
    print('Reject H0')
else:
    print('Do not reject H0')

105.0
130.0
251
251
87
pvalue:  0.0028069482406752645
fstat:   5.934966776686675
Reject H0

4. For StudentsPerformance.csv, using ANOVA find if there is a significant difference in Maths marks depending on the level of parental education

In [89]:
df = pd.read_csv('StudentsPerformance.csv')
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [90]:
df['parental level of education'].value_counts()

parental level of education
some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: count, dtype: int64

In [91]:
s1 = df[df['parental level of education'] == 'some college']['math score']
s2 = df[df['parental level of education'] == "associate's degree"]['math score'] 
s3 = df[df['parental level of education'] == 'high school']['math score'] 
s4 = df[df['parental level of education'] == 'some high school']['math score'] 
s5 = df[df['parental level of education'] == "bachelor's degree"]['math score'] 
s6 = df[df['parental level of education'] == "master's degree"]['math score'] 


fstat,pval = f_oneway(s1,s2,s3,s4,s5,s6)
print('Pvalue: ',pval)
print('fstat: ',fstat)
alpha = 0.05

if pval < alpha:
    print('reject H0')
else:
    print('Do not reject H0')

Pvalue:  5.592272384107223e-06
fstat:  6.521582600453217
reject H0

### Q6. Multiple Linear Regression

Q. Do multiple linear regression on insurance.csv dataset using X=Age and bmi and Y=charges. Do not have Visualization code since we have two colimns

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [2]:
df = pd.read_csv('insurance.csv')
df.head()

   age  gender     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   gender    1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

#### Step 1: Separate dataset into independent and dependent variable

In [4]:
X = df[['age','bmi']]
y = df['charges']

In [5]:
print(X.head())
print(y.head())

   age     bmi
0   19  27.900
1   18  33.770
2   28  33.000
3   33  22.705
4   32  28.880
0    16884.92400
1     1725.55230
2     4449.46200
3    21984.47061
4     3866.85520
Name: charges, dtype: float64

#### Step 2: Split dataset into training and testing

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.20, random_state=0)

In [27]:
print("---Test dataset----")
print(X_test)
print(y_test)

---Test dataset----
      age     bmi
578    52  30.200
610    47  29.370
569    48  40.565
1034   61  38.380
198    51  18.050
...   ...     ...
1084   62  30.495
726    41  28.405
1132   57  40.280
725    30  39.050
963    46  24.795

[268 rows x 2 columns]
578      9724.53000
610      8547.69130
569     45702.02235
1034    12950.07120
198      9644.25250
           ...
1084    15019.76005
726      6664.68595
1132    20709.02034
725     40932.42950
963      9500.57305
Name: charges, Length: 268, dtype: float64

#### Step 3: Fit the model

In [28]:
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

#### Step 4: Make prediction for test data

In [29]:
ypred = model.predict(X_test)

#### Step 5: Evaluate Model

In [30]:
mse = mean_squared_error(y_test, ypred)
mae = mean_absolute_error(y_test, ypred)
r2 = r2_score(y_test, ypred)

print("Mean Squared Error: ", mse)
print("Mean Absolute Error: ",mae)
print("R2 Score: ",r2)

Mean Squared Error:  132649612.7383794
Mean Absolute Error:  8967.270539213538
R2 Score:  0.16640706248734127